[package]
name = "chrome-tracing"
version = "0.1.0"
authors = ["Paul Adenot <paul@paul.cx>"]

[dependencies]
log = "0.4.2"
env_logger = "0.5.10"
slog-async = "2.2.0"
lazy_static = "1.0.0"
slog = { version = "2.2.3", features = ["max_level_trace"] }
slog-term = "2.4.0"


